language: node_js
node_js:
  - "8"
  - "node"
script:
  - npm run lint
  - npm run test
install:
  - npm install
  - npm install --only=dev --ignore-scripts
  - npm install -g codecov --ignore-scripts
script:
  - npm run report-coverage
  - codecov
sudo: false
